### PR TITLE
Use blockstream docker container instead of custom build

### PR DESCRIPTION
**Pull request by bonomat**
I just saw that blockstream maintains a docker image for elementsd. There is no need for ours then :)

Unfortunately the image does not expose any ports by default. Hence the `with_mapped_port`. 

https://github.com/Blockstream/bitcoin-images/tree/master/elementsd

I made a PR because I wanted to test this on a different system :)

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Nice!

Can we patch upstream to include the ports?

**Comment by bonomat** [comment]
> Nice!
> 
> Can we patch upstream to include the ports?

I'll create a PR on their repo and then let's see :)

**Comment by bonomat** [comment]
Note: the `static_analysis` failures come from files of the `sign_transaction` branch. I'll not fix this in this PR here, so please approve/merge if you want to use blockstream's docker image instead of ours :)

**Review by luckysori — APPROVED** [review]

**Review by thomaseizinger — APPROVED** [review]

**Comment by thomaseizinger** [comment]
> Note: the `static_analysis` failures come from files of the `sign_transaction` branch. I'll not fix this in this PR here, so please approve/merge if you want to use blockstream's docker image instead of ours :)

Yup, I filed an issue with the client here: https://github.com/thomaseizinger/rust-jsonrpc-client/issues/3

**Pull request merged**
